site_name: NovaScope-exemplary-downstream-analysis
site_url: https://seqscope.github.io/NovaScope-exemplary-downstream-analysis

# Repository
repo_name: seqscope/NovaScope
repo_url: https://github.com/seqscope/NovaScope-exemplary-downstream-analysis

# Theme configuration
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.indexes
  - navigation.sections
  - content.code.annotate
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference
#    primary: 'deep purple'
#    accent: 'lime'
#  palette:
#    primary: indigo
#    accent: grey
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Navigation structure
nav:
  - Home: 
      - Introduction: index.md
      #- Spatial Transcriptomics Analysis: home/hex_idx_overview.md
      - Documentation Overview: home/documentation_overview.md
  - Installation: 
      - Installing NEDA: installation/installation.md
      - Example Datasets: installation/example_data.md
  - Spatial Transcriptomics Analysis:
      - Introduction: analysis/hex_idx/intro.md
      - Preparing Input:
          - Input Data: analysis/hex_idx/prepare_data.md
          - Job Configuration: analysis/hex_idx/job_config.md
      - Analysis:
        - Preprocessing: analysis/hex_idx/step1-preprocess.md
        - Latent Dirichlet allocation (LDA) Factorization: analysis/hex_idx/step2a-LDA.md
        - Seurat Clustering: analysis/hex_idx/step2b-seurat.md
        - Transform : analysis/hex_idx/step3-transform.md
        - Pixel-level Decoding: analysis/hex_idx/step4-decode.md
  - Preliminary Single-Cell Analysis:
      - Introduction: analysis/cell_idx/intro.md
      - Preparing input: analysis/cell_idx/prepare_data.md
      - Analysis:
        - Create Cell-indexed SGE: analysis/cell_idx/step1-cell_SGE.md
        - Seurat Clustering: analysis/cell_idx/step2-Seurat-clustering.md


# Markdown Extensions
markdown_extensions:
  - admonition
#  - codehilite:
#      guess_lang: false 
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
      css_class: 'highlight'
  - pymdownx.superfences
# - pymdownx.inlinehilite


plugins:
  - search
  - open-in-new-tab

# Extra CSS
extra_css:
  - css/custom.css