site_name: NovaScope-exemplary-downstream-analysis
site_url: https://seqscope.github.io/NovaScope-exemplary-downstream-analysis

# Repository
repo_name: seqscope/NovaScope
repo_url: https://github.com/seqscope/NovaScope-exemplary-downstream-analysis

# Theme configuration
theme:
  name: material
#  palette:
#    primary: 'deep purple'
#    accent: 'lime'
  palette:
    primary: indigo
    accent: grey
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Navigation structure
nav:
  - Home: index.md
  - Preparation:
      - Installing NovaScope-exemplary-downstream-analysis (NEDA): preparation/prestep1-setup.md
      - Preparing Input: preparation/prestep2-input.md
  - LDA+FICTURE Analysis:
      - Preprocessing: LDA/step1-preprocess.md
      - LDA Factorization: LDA/step2a-LDA.md
      - Transform : LDA/step3-transform.md
      - Pixel-level Decoding: LDA/step4-decode.md
  - Seurat+FICTURE Analysis:
      - Preprocessing: Seurat/step1-preprocess.md
      - Seurat Clustering: Seurat/step2b-seurat.md
      - Transform : Seurat/step3-transform.md
      - Pixel-level Decoding: Seurat/step4-decode.md

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
