library(Seurat)
library(ggplot2)
library(patchwork)
library(dplyr)
library(tidyverse)
library(stringr)
library(cowplot)
library(optparse)
library(grDevices)
library(RColorBrewer)

# Define the command line options
option_list <- list(
  make_option(c("-i", "--input_rds"), type = "character", default = "", help = "Input RDS generated by seurat_analysis.R", metavar = "DIR"),
  make_option(c("-o", "--output_dir"), type = "character", default = "", help = "Output directory.", metavar = "DIR"),
  make_option(c("-r", "--resolution"), type = "numeric", default = 1, help = "The resolution for clustering.", metavar = "NUM"),
  make_option(c("-f", "--format"), type= "character", default = "png", help = "The format of the output file.", metavar = "STRING")
  #make_option(c("-t", "--font"), type= "character", default = "DejaVu Sans", help = "The font for the text in the plot.", metavar = "STRING")
)

opt_parser <- OptionParser(option_list = option_list,
                           usage = "Usage: %prog [options]",
                           description = paste(
                             "Load R if needed:",
                             "  module load R/4.2.0",
                             "Run the script:",
                             "  Rscript seurat_analysis_viz.R -i <input_rds> -o <output_dir> -r <resolution> -f <format>",
                             sep = "\n")
)
opts = parse_args(opt_parser)

# Script Test
script_test <- FALSE
if (script_test){
  opts$input_rds <-  "/nfs/turbo/sph-hmkang/index/data/weiqiuc/testruns/neda/results_v3/deep/Seurat/deep_cutoff500_SCT.RDS" 
  opts$output_dir <- "/nfs/turbo/sph-hmkang/index/data/weiqiuc/testruns/neda/results_v3/deep/Seurat/"
  opts$resolution <- 1
  opts$format <- "pdf"
  #opts$font <- "DejaVu Sans"
}

# Input/Output File/ directory
if (!dir.exists(opts$output_dir)) {
  dir.create(opts$output_dir, recursive = TRUE)
}

input_basename <- basename(opts$input_rds)
output_prefix<- paste0(opts$output_dir,"/", str_remove(input_basename, "_SCT.RDS"))

adata <- readRDS(opts$input_rds)
#===============================================================================
#
# General functions for visualization in R.
#
#===============================================================================

# Custom theme for ggplot2
theme_wc <- function(base_size = 14) {
  theme_bw(base_size = base_size) %+replace%
    theme(
      plot.title = element_text(size = rel(1), margin = margin(0,0,5,0), hjust = 0.5),
      plot.subtitle = element_text(size = rel(0.70), hjust = 0.5),
      #axis
      axis.title = element_text(size = rel(0.85)),
      axis.text = element_text(size = rel(0.70)),
      #legend
      legend.title = element_text(size = rel(0.85)),
      legend.text = element_text(size = rel(0.70)),
      legend.key = element_rect(fill = "transparent", colour = NA),
      legend.key.size = unit(1.5, "lines"),
      legend.background = element_rect(fill = "transparent", colour = NA),
      #text
      #text=element_text(family=font, colour = "black")
    )
}


# Function to prep color palette for a large number of colors
extend_palette <- function(num_colors, color_space = "Lab") {
  palette_max_colors <- c(Set3 = 12, Set1 = 9, Dark2 = 8, Paired = 12)
  combined_palette <- c()
  for (palette_name in names(palette_max_colors)) {
    if (num_colors > length(combined_palette)) {
      n_colors <- min(num_colors, palette_max_colors[palette_name])
      combined_palette <- c(combined_palette, brewer.pal(n_colors, palette_name))
      combined_palette <- unique(combined_palette)
    }
  }
  if (num_colors > length(combined_palette)) {
    additional_colors_needed <- num_colors - length(combined_palette)
    color_ends <- if (color_space == "Lab") { c("red", "blue", "green", "yellow") } else {c("red", "blue") }
    color_generator <- colorRampPalette(color_ends, space = color_space)
    additional_colors <- color_generator(additional_colors_needed)
    combined_palette <- c(combined_palette, additional_colors)
  }
  return(combined_palette[1:num_colors])
}

#==============================================================================
#
# Generate figures
#
#==============================================================================
# function to perform clustering and imaging at a given resolution
calculate_plot_dimensions <- function(adata) {
  x_range <- range(adata@meta.data$X, na.rm = TRUE)
  y_range <- range(adata@meta.data$Y, na.rm = TRUE)
  aspect_ratio <- (x_range[2] - x_range[1]) / (y_range[2] - y_range[1])
  return(aspect_ratio)
}

viz_clusters <- function(adata, resolution, output_prefix, viz_format,  base_size=10) {
  # Basic settings
  aspect_ratio <- calculate_plot_dimensions(adata)
  base_filename <- paste0(output_prefix, "_res", resolution)

  # Clustering
  adata <- FindClusters(adata, resolution = resolution)
  
  # Prep color palette
  Ncluster=length(summary(adata@meta.data$seurat_clusters))  
  my_color_palette <- extend_palette(Ncluster, "Lab")
  
  # Dimension Plot
  dim_panel <- DimPlot(adata, label = TRUE) + ggtitle(paste("Dim Plot, Resolution:", resolution))+ 
    theme_wc() +
    scale_color_manual(values = my_color_palette, name="Seurat clusters") +  
    guides(color = guide_legend(override.aes = list(size = 5))) 
  
  # Spatial Plot
  spatial_panel <- ggplot(adata@meta.data, aes(x = Y, y = X, col = as.factor(seurat_clusters))) + 
    geom_point(size = .1) + 
    theme_wc() + 
    coord_fixed() +  # Ensure 1:1 aspect ratio
    scale_color_manual(values = my_color_palette, name="Seurat clusters") + 
    guides(color = guide_legend(override.aes = list(size = 5))) +
    ggtitle(paste0("Spatial plot, Resolution: ", resolution))
  
  # Combine plots
  combined_plot <- plot_grid(
    dim_panel + theme(legend.position = "none"), 
    spatial_panel + theme(legend.position = "none"), 
    get_legend(dim_panel),
    ncol = 3,
    rel_widths = c(1, 1/aspect_ratio, 0.2)
  )
  
  # Add a white background
  final_plot <- ggdraw() + 
    draw_plot(combined_plot, 0, 0, 1, 1) + 
    theme(plot.background = element_rect(fill = "white", colour = NA))
  
  clusterfig <-paste0(base_filename, "_DimSpatial.", viz_format)
  ggsave(clusterfig, 
         plot = final_plot, 
         width = base_size * (1.2 + aspect_ratio),
         height = base_size, units="in",
         dpi = 300)
  # print out the location of the output files
  print(paste0("The output files are saved in the following location: ", clusterfig))
  return(adata)
}

# Loop over resolutions
message(paste0(" - Clustering and imaging at resolution ", opts$resolution))
adata <- viz_clusters(adata, opts$resolution, output_prefix, opts$format, base_size=7)
